---
- name: Install dependencies
  become: yes
  package:
    name:
      - p7zip-full
      - xorriso
      - gpg
      - curl
    state: present
  with_items:
    - p7zip-full
    - xorriso
    - gpg
    - curl
  when: ansible_os_family != "Darwin"

- name: Install dependencies (macOS)
  package:
    name: 
      - p7zip
      - xorriso
      - gnupg
      - curl
    state: present
  when: ansible_os_family == "Darwin"

- name: Create the temporary directory
  file:
    path: "{{ target_dir }}"
    state: directory
